[package]
name = "tour-of-rust"
version = "0.1.0"
authors = ["saccho <saccho956@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
